name: flutter_immobilier
description: Application immobilière

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  tuple: ^2.0.0
  json_annotation: ^4.0.1
  provider: ^6.0.2
  get_it: ^7.2.0
  environment_config: ^3.0.0
  fluttertoast: ^8.0.9
  multi_select_flutter: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
flutter:
  uses-material-design: true
